spring.datasource.url=${RDS_URL}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.s3.bucket=video-editor-scenith
app.s3.region=eu-north-1

app.base-dir=/tmp
app.global-elements-dir=elements/

app.ffmpeg-path=s3://video-editor-scenith/binaries/linux/ffmpeg
app.ffprobe-path=s3://video-editor-scenith/binaries/linux/ffprobe

app.frontend.url=${FRONTEND_URL:https://your-domain.com}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.security.oauth2.client.registration.google.client-id=475177334034-ufjdi8pebqvbgf9ogv0gs85nq9588a8m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

jwt.secret=${JWT_SECRET}

server.port=5000