## Production configuration for AWS
#spring.profiles.active=prod
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=false
#
#app.ffmpeg-path=${FFMPEG_PATH:/usr/local/bin/ffmpeg}
#app.frontend.url=${FRONTEND_URL}
#
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#jwt.secret=${JWT_SECRET}
#
#server.port=5000